# Generated by Django 2.2.6 on 2019-11-13 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serials', '0001_initial'),
        ('episodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('episodes', models.ManyToManyField(to='episodes.Episode')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serials.Serial')),
            ],
        ),
    ]
