# Generated by Django 2.2.7 on 2019-11-14 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0004_remove_serial_seasons'),
        ('seasons', '0002_remove_season_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='serial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='serials.Serial'),
        ),
    ]
