# Generated by Django 2.2.7 on 2019-11-14 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0003_season_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='episodes',
        ),
    ]
