# Generated by Django 2.2.6 on 2019-11-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('premiere_date', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(to='categories.Category')),
            ],
        ),
    ]
