# Generated by Django 2.2.7 on 2019-11-14 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0003_auto_20191114_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serial',
            name='seasons',
        ),
    ]
